# @package _global_
training:
  epochs: 15
  early_stopping_patience: -1
  load_checkpoint: false
  dataloader_workers: 8
  gradient_clip_val: 1.0
  log_profit: true
  loss_function: mse
  checkpoints:
    enabled: true
    filename: "${constants.model_codename}_{epoch}_{val_loss:.2f}_{other_metric:.2f}"
    dir: checkpoints
    save_top_k: -1
